### ISSUE TITLE
 Unable to prepare setup for platform baxi_thermostat.climate: Unable to set up component. 

### ISSUE THREAD

**Issue by lobernat** [vipial1/BAXI_thermostat#1]
Unable to prepare setup for platform baxi_thermostat.climate: Unable to set up component. 

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/baxi_thermostat/BaxiAPI.py:130
Integration: BAXI Thermostat (documentation)
First occurred: 1:24:36 PM (1 occurrences)
Last logged: 1:24:36 PM

Error during setup of component baxi_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/baxi_thermostat/__init__.py", line 24, in async_setup
    await api.bootstrap()
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 45, in bootstrap
    if not await self._load_stored_token() or not await self.connection_status():
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 135, in connection_status
    response = await self.async_get_request(api_endpoint)
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 130, in async_get_request
    return response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vipial1** [comment]
My fault. I found the bug. Should be fixed in the last commits.

Please, try again and reopen the issue if need.
