### ISSUE TITLE
BAXI Mago with GW-16 creating Device with no entities

### ISSUE THREAD

**Issue by srodighiero** [vipial1/BAXI_thermostat#7]
Hi, 

The integration is setup with success, but as in title, it creates the device (the gateway) but no entities, any ideas/suggestions?

Thank you
![image](https://user-images.githubusercontent.com/4833164/188851182-1e7def67-5b3a-4fd9-a9d3-e2102ed6eac9.png)

This the logs:
Logger: homeassistant.components.climate
Source: custom_components/baxi_thermostat/BaxiAPI.py:138
Integration: Climate (documentation, issues)
First occurred: 11:49:06 (2 occurrences)
Last logged: 12:11:57

baxi_thermostat: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
    await task
  File "/config/custom_components/baxi_thermostat/climate.py", line 125, in async_update
    pressure = await self._baxi_api.get_water_pressure()
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 244, in get_water_pressure
    return await self.async_get_request(api_endpoint)
  File "/config/custom_components/baxi_thermostat/BaxiAPI.py", line 138, in async_get_request
    return response.json() if response else response
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

NOTE: I have still to connect the GW-16 to the boiler, could it be this the reason of the problem?

**Comment by srodighiero** [comment]
As predicted, the reason was that the boiler was not connected yet. Maybe you can use these logs to improve the config flow/ui and report maybe a warning message or similar. I would in any case suggest to add this note to the README.
