### ISSUE TITLE
Error message when changing preset

### ISSUE THREAD

**Issue by srodighiero** [vipial1/BAXI_thermostat#8]
Integration is working fine, however every time the preset is changed, even if the change occurs eventually, an error log is raised, as an example below:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/baxi_thermostat/climate.py:156 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 18:40:23 (4 occurrences) 
Last logged: 18:42:03

[547278154448] cannot unpack non-iterable NoneType object
[547222073936] cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/baxi_thermostat/climate.py", line 156, in async_set_preset_mode
    baxi_preset_mode, program = self._attr_preset_mode = preset_mode_ha_to_baxi(
TypeError: cannot unpack non-iterable NoneType object

Noticed that this happens when changing directly from the "more info" window, and nto from a card

**Comment by vipial1** [comment]
Which presets mode do you have?
